version: 2.1
orbs:
  revenuecat: revenuecat/sdks-common-config@3.0.0

parameters:
  action:
    type: enum
    enum: [default, update_paywall_templates]
    default: default

jobs:

  update-paywall-templates:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - revenuecat/install-gem-unix-dependencies:
          cache-version: v1
      - revenuecat/setup-git-credentials
      - run:
          name: Update paywall templates
          command: bundle exec fastlane update_paywall_templates
  
  trigger-downstream-updates:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - run:
          name: Trigger downstream updates in purchases-android
          command: bundle exec fastlane trigger_downstream_updates repo_name:purchases-android

workflows:

  on-main-branch:
    when:
      and:
        - equal: [ << pipeline.git.branch >> , main ]
        - equal: [ << pipeline.parameters.action >> , default ]
    jobs:
      - trigger-downstream-updates

  update-paywall-templates:
    when:
      equal: [ << pipeline.parameters.action >>, update_paywall_templates ]
    jobs:
      - update-paywall-templates
